"""add phase 6 columns

Revision ID: 3e86727dbcee
Revises: a3f1c8e2d905
Create Date: 2026-06-04 14:51:48.393965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e86727dbcee'
down_revision = 'a3f1c8e2d905'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phase_informed_voting', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('phase6_polis_conversation_id', sa.String(length=50), nullable=True))

    with op.batch_alter_table('featured_statements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phase6_polis_statement_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('participations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phase6_polis_xid', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participations', schema=None) as batch_op:
        batch_op.drop_column('phase6_polis_xid')

    with op.batch_alter_table('featured_statements', schema=None) as batch_op:
        batch_op.drop_column('phase6_polis_statement_id')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_column('phase6_polis_conversation_id')
        batch_op.drop_column('phase_informed_voting')

    # ### end Alembic commands ###
