"""add closed_at public_username revealed_at

Revision ID: 65de8d5c7314
Revises: 
Create Date: 2026-05-12 11:47:37.989901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65de8d5c7314'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('closed_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('participations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_username', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('revealed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participations', schema=None) as batch_op:
        batch_op.drop_column('revealed_at')
        batch_op.drop_column('public_username')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_column('closed_at')

    # ### end Alembic commands ###
