"""add hidden field to arguments

Revision ID: 99f8b42af697
Revises: b959def66404
Create Date: 2026-05-21 21:09:22.829896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99f8b42af697'
down_revision = 'b959def66404'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('arguments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hidden', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('arguments', schema=None) as batch_op:
        batch_op.drop_column('hidden')

    # ### end Alembic commands ###
