"""add phase6_card_order to participations

Revision ID: f667548e9519
Revises: 3e86727dbcee
Create Date: 2026-06-04 21:36:08.998579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f667548e9519'
down_revision = '3e86727dbcee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phase6_card_order', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participations', schema=None) as batch_op:
        batch_op.drop_column('phase6_card_order')

    # ### end Alembic commands ###
