/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the current browser session and its site-wide capabilities */
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return participant-facing conversation groups for one space */
        get: operations["getConversationLane"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{slug}/about": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the participant-safe record for one conversation */
        get: operations["getConversationAbout"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{slug}/identity-reveal": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        /** Return the participant's identity-reveal timeline and capability */
        get: operations["getIdentityReveal"];
        put?: never;
        /**
         * Permanently link the participant's Wikimedia username and pseudonym
         * @description Irreversible and idempotent. A replay returns the existing public link with HTTP 200.
         */
        post: operations["createIdentityReveal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{slug}/pseudonym-suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return available pseudonym suggestions for a join form */
        get: operations["getPseudonymSuggestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{slug}/participation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Join a conversation with a globally unique pseudonym
         * @description Idempotent for an already joined participant; a replay returns the existing participation with HTTP 200.
         */
        post: operations["createParticipation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{slug}/explore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the current participant Explore queue state */
        get: operations["getExploreState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{slug}/arguments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Return the participant's argument-mapping task state
         * @description Contribution status, stable argument ordering, prioritization gates, and capabilities are computed server-side. Aggregate importance counts are withheld during the open phase to avoid anchoring.
         */
        get: operations["getArgumentMapping"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{slug}/featured-statements/{featuredStatementId}/arguments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit one argument for a featured-statement side
         * @description Idempotent for an identical replay. One contribution per participant, featured statement, and side is enforced by the database.
         */
        post: operations["createArgument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{slug}/featured-statements/{featuredStatementId}/contributions/{side}/skip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Explicitly skip one argument-contribution side
         * @description Idempotent state replacement; repeated PUT requests keep the side skipped.
         */
        put: operations["putArgumentContributionSkip"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{slug}/arguments/{argumentId}/priority": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set whether an argument is one of the participant's priorities
         * @description Idempotent state replacement serialized per participant, featured statement, and side.
         */
        put: operations["putArgumentPriority"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{slug}/flags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Flag a statement or argument for moderator review
         * @description Idempotent for the same participant, target, and category while a flag remains open. Other requires an explanation.
         */
        post: operations["createContentFlag"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{slug}/statements/{statementId}/vote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set the participant's vote on an Explore statement
         * @description Idempotent: repeated PUT requests replace the vote with the requested choice.
         */
        put: operations["putExploreVote"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{slug}/statements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit a new or derivative statement during Explore
         * @description A durable idempotency receipt prevents duplicate upstream statements. Reusing a completed key with the same body returns HTTP 200; a pending receipt reports an unknown outcome.
         */
        post: operations["createStatement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return this OpenAPI document */
        get: operations["getOpenApiDocument"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SessionResponse: {
            data: components["schemas"]["Session"];
        };
        Session: {
            /** @enum {string} */
            state: "anonymous" | "authenticated" | "demo";
            user: components["schemas"]["SessionUser"] | null;
            capabilities: components["schemas"]["SiteCapabilities"];
            csrfToken: string;
            links: components["schemas"]["SessionLinks"];
        };
        SessionUser: {
            username: string;
            emailable: boolean;
        };
        SiteCapabilities: {
            administerSite: boolean;
        };
        SessionLinks: {
            login: string;
            logout: string;
        };
        ConversationLaneResponse: {
            data: components["schemas"]["ConversationLane"];
        };
        ConversationLane: {
            /** @enum {string} */
            space: "real" | "demo";
            authenticated: boolean;
            groups: components["schemas"]["ConversationGroups"];
        };
        ConversationGroups: {
            needsAttention: components["schemas"]["ConversationCard"][];
            caughtUp: components["schemas"]["ConversationCard"][];
            inactive: components["schemas"]["ConversationCard"][];
            archived: components["schemas"]["ConversationCard"][];
            available: components["schemas"]["ConversationCard"][];
            moderating: components["schemas"]["ConversationCard"][];
        };
        ConversationCard: {
            slug: string;
            title: string;
            /** @enum {string} */
            relationship: "joined" | "available" | "moderating";
            participantState: ("needs_attention" | "caught_up" | "inactive" | "archived") | null;
            pseudonym: string | null;
            /** @enum {string} */
            status: "open" | "paused" | "archived";
            phases: string[];
            statementsRemaining: number | null;
            scheduledTransition: components["schemas"]["ScheduledTransition"] | null;
            outputs: components["schemas"]["ConversationOutput"][];
            capabilities: components["schemas"]["ConversationCapabilities"];
            links: components["schemas"]["ConversationLinks"];
        };
        ConversationAboutResponse: {
            data: components["schemas"]["ConversationAbout"];
        };
        IdentityRevealResponse: {
            data: components["schemas"]["IdentityReveal"];
        };
        CreateIdentityRevealRequest: {
            /** @constant */
            confirm: true;
        };
        IdentityReveal: {
            slug: string;
            title: string;
            /** @enum {string} */
            state: "pending" | "open" | "revealed" | "expired";
            pseudonym: string;
            wikimediaUsername: string;
            publicUsername: string | null;
            timeline: components["schemas"]["IdentityRevealTimeline"];
            capabilities: components["schemas"]["IdentityRevealCapabilities"];
            links: components["schemas"]["IdentityRevealLinks"];
        };
        IdentityRevealTimeline: {
            /** Format: date-time */
            closedAt: string;
            /** Format: date-time */
            opensAt: string;
            /** Format: date-time */
            closesAt: string;
            /** Format: date-time */
            nextBoundaryAt: string | null;
            daysRemaining: number;
        };
        IdentityRevealCapabilities: {
            revealIdentity: boolean;
        };
        IdentityRevealLinks: {
            self: string;
            conversation: string;
            about: string;
        };
        PseudonymSuggestionsResponse: {
            data: {
                pseudonyms: string[];
            };
        };
        CreateParticipationRequest: {
            pseudonym: string;
            /** @default false */
            notifyEmail: boolean;
            /** @default false */
            notifyTalkPage: boolean;
        };
        ParticipationResponse: {
            data: components["schemas"]["Participation"];
        };
        Participation: {
            pseudonym: string;
            notifications: {
                email: boolean;
                talkPage: boolean;
            };
            /** @enum {string|null} */
            eligibilityStatus: "eligible" | "not_required" | null;
            links: {
                conversation: string;
                about: string;
            };
        };
        ExploreStateResponse: {
            data: components["schemas"]["ExploreState"];
        };
        ExploreState: {
            slug: string;
            title: string;
            pseudonym: string;
            currentStatement: components["schemas"]["ExploreStatement"] | null;
            progress: components["schemas"]["ExploreProgress"];
            newStatement: components["schemas"]["NewStatementAvailability"];
            capabilities: components["schemas"]["ExploreCapabilities"];
            links: components["schemas"]["ExploreLinks"];
        };
        ExploreStatement: {
            id: number;
            text: string;
            isMeta: boolean;
            isSeed: boolean;
        };
        ExploreProgress: {
            completed: number;
            total: number;
            remaining: number;
            allDone: boolean;
        };
        NewStatementAvailability: {
            unlocked: boolean;
            unlockAfter: number;
            quota: number;
            used: number;
            remaining: number;
        };
        ExploreCapabilities: {
            vote: boolean;
            suggestWording: boolean;
            submitNewStatement: boolean;
        };
        ExploreLinks: {
            self: string;
            about: string;
            conversation: string;
            arguments?: string;
        };
        ExploreVoteRequest: {
            /** @enum {string} */
            choice: "agree" | "pass" | "disagree";
            /**
             * @description Optional local reason for a pass vote. Valid only when choice is pass.
             * @enum {string}
             */
            passReason?: "unsure" | "confusing";
        };
        ExploreVoteResponse: {
            data: components["schemas"]["ExploreVoteReceipt"];
        };
        ExploreVoteReceipt: {
            statementId: number;
            /** @enum {string} */
            choice: "agree" | "pass" | "disagree";
            /** @enum {string|null} */
            passReason: "unsure" | "confusing" | null;
            links: {
                explore: string;
            };
        };
        ArgumentMappingResponse: {
            data: components["schemas"]["ArgumentMapping"];
        };
        ArgumentMapping: {
            slug: string;
            title: string;
            pseudonym: string;
            progress: components["schemas"]["ArgumentMappingProgress"];
            featuredStatements: components["schemas"]["ArgumentFeaturedStatement"][];
            capabilities: components["schemas"]["ArgumentMappingCapabilities"];
            links: components["schemas"]["ArgumentMappingLinks"];
        };
        ArgumentMappingProgress: {
            completed: number;
            total: number;
            allDone: boolean;
            currentFeaturedStatementId: number | null;
        };
        ArgumentFeaturedStatement: {
            id: number;
            statement: components["schemas"]["ArgumentStatement"];
            contributionsComplete: boolean;
            complete: boolean;
            sides: {
                pro: components["schemas"]["ArgumentSide"];
                con: components["schemas"]["ArgumentSide"];
            };
            capabilities: {
                flagStatement: boolean;
            };
        };
        ArgumentStatement: {
            id: number;
            text: string;
        };
        ArgumentSide: {
            contribution: components["schemas"]["ArgumentContribution"];
            prioritization: components["schemas"]["ArgumentPrioritization"];
            arguments: components["schemas"]["ArgumentItem"][];
        };
        ArgumentContribution: {
            /** @enum {string} */
            status: "pending" | "submitted" | "skipped";
            argumentId: number | null;
            capabilities: {
                submit: boolean;
                skip: boolean;
            };
        };
        ArgumentPrioritization: {
            available: boolean;
            requiredArgumentCount: number;
            argumentCount: number;
            selectionBudget: number;
            selectedCount: number;
            complete: boolean;
        };
        ArgumentItem: {
            id: number;
            body: string;
            own: boolean;
            selected: boolean;
            capabilities: {
                prioritize: boolean;
                flag: boolean;
            };
        };
        ArgumentMappingCapabilities: {
            contribute: boolean;
            prioritize: boolean;
            flag: boolean;
        };
        ArgumentMappingLinks: {
            self: string;
            about: string;
            conversation: string;
            explore?: string;
        };
        CreateArgumentRequest: {
            /** @enum {string} */
            side: "pro" | "con";
            body: string;
        };
        ArgumentCommandLinks: {
            arguments: string;
        };
        ArgumentSubmissionResponse: {
            data: components["schemas"]["ArgumentSubmissionReceipt"];
        };
        ArgumentSubmissionReceipt: {
            featuredStatementId: number;
            /** @enum {string} */
            side: "pro" | "con";
            /** @constant */
            status: "submitted";
            argument: components["schemas"]["ArgumentItem"];
            links: components["schemas"]["ArgumentCommandLinks"];
        };
        ArgumentSkipResponse: {
            data: components["schemas"]["ArgumentSkipReceipt"];
        };
        ArgumentSkipReceipt: {
            featuredStatementId: number;
            /** @enum {string} */
            side: "pro" | "con";
            /** @constant */
            status: "skipped";
            links: components["schemas"]["ArgumentCommandLinks"];
        };
        ArgumentPriorityRequest: {
            selected: boolean;
        };
        ArgumentPriorityResponse: {
            data: components["schemas"]["ArgumentPriorityReceipt"];
        };
        ArgumentPriorityReceipt: {
            argumentId: number;
            selected: boolean;
            selectedCount: number;
            selectionBudget: number;
            links: components["schemas"]["ArgumentCommandLinks"];
        };
        CreateContentFlagRequest: {
            /** @enum {string} */
            contentType: "statement" | "argument";
            targetId: number;
            /** @enum {string} */
            category: "personal_attack" | "privacy" | "off_topic" | "other";
            detail?: string | null;
        };
        ContentFlagResponse: {
            data: components["schemas"]["ContentFlagReceipt"];
        };
        ContentFlagReceipt: {
            /** @enum {string} */
            contentType: "statement" | "argument";
            targetId: number;
            /** @enum {string} */
            category: "personal_attack" | "privacy" | "off_topic" | "other";
            /** @constant */
            status: "open";
            created: boolean;
            links: {
                conversation: string;
            };
        };
        CreateStatementRequest: {
            text: string;
            derivedFromStatementId?: number | null;
        };
        StatementCreationResponse: {
            data: components["schemas"]["StatementCreationReceipt"];
        };
        StatementCreationReceipt: {
            statementId: number;
            /** @enum {string} */
            kind: "new" | "derivative";
            derivedFromStatementId: number | null;
            newStatementQuotaRemaining: number;
            links: {
                explore: string;
            };
        };
        ConversationAbout: {
            slug: string;
            title: string;
            descriptionHtml: string | null;
            outroHtml: string | null;
            /** @enum {string} */
            status: "open" | "paused" | "archived";
            phases: components["schemas"]["ConversationPhase"][];
            scheduledTransition: components["schemas"]["ScheduledTransition"] | null;
            pseudonym: string | null;
            statistics: components["schemas"]["ConversationStatistics"];
            personal: components["schemas"]["PersonalContributions"] | null;
            outputs: components["schemas"]["ConversationOutput"][];
            moderation: components["schemas"]["ConversationModeration"];
            capabilities: components["schemas"]["ConversationAboutCapabilities"];
            links: components["schemas"]["ConversationAboutLinks"];
        };
        ConversationPhase: {
            key: string;
            label: string;
        };
        ConversationStatistics: {
            participants: number | null;
            statementVotes: number | null;
            statements: number | null;
            arguments: number;
            argumentContributors: number;
        };
        PersonalContributions: {
            statementsSuggested: number;
            statementVotes: number | null;
            statementVotesAvailable: boolean;
            argumentsAdded: number;
            argumentsRated: number;
        };
        ConversationModeration: {
            eventCount: number;
            href: string;
        };
        ConversationAboutCapabilities: {
            participate: boolean;
            moderate: boolean;
        };
        ConversationAboutLinks: {
            self: string;
            conversation: string;
        };
        ScheduledTransition: {
            /** Format: date-time */
            at: string;
            target: string;
            targetLabel: string;
        };
        ConversationOutput: {
            key: string;
            label: string;
            status: string;
            ready: boolean;
            href: string | null;
        };
        ConversationCapabilities: {
            join: boolean;
            participate: boolean;
            moderate: boolean;
        };
        ConversationLinks: {
            self: string;
            about: string;
            explore?: string;
            arguments?: string;
            identityReveal?: string;
            admin?: string;
        };
        ErrorResponse: {
            error: {
                code: string;
                message: string;
                details?: unknown;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current session */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
        };
    };
    getConversationLane: {
        parameters: {
            query?: {
                space?: "real" | "demo";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Conversation lane */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationLaneResponse"];
                };
            };
            /** @description Invalid space */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getConversationAbout: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Conversation record */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationAboutResponse"];
                };
            };
            /** @description The current browser cannot access this conversation */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conversation not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getIdentityReveal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Identity-reveal state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentityRevealResponse"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conversation is not closed or participant has not joined */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createIdentityReveal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateIdentityRevealRequest"];
            };
        };
        responses: {
            /** @description Existing reveal returned on replay */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentityRevealResponse"];
                };
            };
            /** @description Identity permanently linked */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentityRevealResponse"];
                };
            };
            /** @description Explicit confirmation missing */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Reveal window is not open */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getPseudonymSuggestions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fresh pseudonym suggestions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PseudonymSuggestionsResponse"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createParticipation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateParticipationRequest"];
            };
        };
        responses: {
            /** @description Existing participation returned for an idempotent replay */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParticipationResponse"];
                };
            };
            /** @description Participation created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParticipationResponse"];
                };
            };
            /** @description Invalid command */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Access or eligibility denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Pseudonym conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getExploreState: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current Explore state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExploreStateResponse"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conversation access denied or participant banned */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Participation or Explore phase is not active */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Voting service unavailable */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getArgumentMapping: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current argument-mapping state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArgumentMappingResponse"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conversation access is denied or the participant is banned */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conversation not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Participation is missing or argument mapping is not open */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createArgument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                featuredStatementId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateArgumentRequest"];
            };
        };
        responses: {
            /** @description Existing identical argument returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArgumentSubmissionResponse"];
                };
            };
            /** @description Argument created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArgumentSubmissionResponse"];
                };
            };
            /** @description Invalid argument */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Access denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conversation or featured statement not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Phase conflict or a different argument already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    putArgumentContributionSkip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                featuredStatementId: number;
                side: "pro" | "con";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Contribution side is skipped */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArgumentSkipResponse"];
                };
            };
            /** @description Invalid side */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Access denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conversation or featured statement not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Phase conflict or the side already has an argument */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    putArgumentPriority: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                argumentId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArgumentPriorityRequest"];
            };
        };
        responses: {
            /** @description Priority state stored */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArgumentPriorityResponse"];
                };
            };
            /** @description Invalid selection state */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Access denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conversation or argument not found/available */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Contribution gate, volume gate, budget, or phase conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createContentFlag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateContentFlagRequest"];
            };
        };
        responses: {
            /** @description Existing open flag returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentFlagResponse"];
                };
            };
            /** @description Flag created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentFlagResponse"];
                };
            };
            /** @description Invalid target, category, or missing Other explanation */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Access denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conversation or target not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Participation missing or flags closed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Statement validation service unavailable */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    putExploreVote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                statementId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExploreVoteRequest"];
            };
        };
        responses: {
            /** @description Vote stored */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExploreVoteResponse"];
                };
            };
            /** @description Invalid vote choice */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conversation access denied or participant banned */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conversation or statement not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Participation or Explore phase is not active */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Voting service unavailable */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createStatement: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStatementRequest"];
            };
        };
        responses: {
            /** @description Completed command replay */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatementCreationResponse"];
                };
            };
            /** @description Statement created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatementCreationResponse"];
                };
            };
            /** @description Invalid request, idempotency key, or parent statement */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conversation access denied or participant banned */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Quota, derivative similarity, idempotency conflict, or unknown outcome */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The upstream command outcome is unknown */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getOpenApiDocument: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OpenAPI 3.1 document */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
