/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the current browser session and its site-wide capabilities */
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return participant-facing conversation groups for one space */
        get: operations["getConversationLane"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{slug}/about": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the participant-safe record for one conversation */
        get: operations["getConversationAbout"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{slug}/pseudonym-suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return available pseudonym suggestions for a join form */
        get: operations["getPseudonymSuggestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{slug}/participation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Join a conversation with a globally unique pseudonym
         * @description Idempotent for an already joined participant; a replay returns the existing participation with HTTP 200.
         */
        post: operations["createParticipation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{slug}/explore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the current participant Explore queue state */
        get: operations["getExploreState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{slug}/statements/{statementId}/vote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set the participant's vote on an Explore statement
         * @description Idempotent: repeated PUT requests replace the vote with the requested choice.
         */
        put: operations["putExploreVote"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{slug}/statements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit a new or derivative statement during Explore
         * @description A durable idempotency receipt prevents duplicate upstream statements. Reusing a completed key with the same body returns HTTP 200; a pending receipt reports an unknown outcome.
         */
        post: operations["createStatement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return this OpenAPI document */
        get: operations["getOpenApiDocument"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SessionResponse: {
            data: components["schemas"]["Session"];
        };
        Session: {
            /** @enum {string} */
            state: "anonymous" | "authenticated" | "demo";
            user: components["schemas"]["SessionUser"] | null;
            capabilities: components["schemas"]["SiteCapabilities"];
            csrfToken: string;
            links: components["schemas"]["SessionLinks"];
        };
        SessionUser: {
            username: string;
            emailable: boolean;
        };
        SiteCapabilities: {
            administerSite: boolean;
        };
        SessionLinks: {
            login: string;
            logout: string;
        };
        ConversationLaneResponse: {
            data: components["schemas"]["ConversationLane"];
        };
        ConversationLane: {
            /** @enum {string} */
            space: "real" | "demo";
            authenticated: boolean;
            groups: components["schemas"]["ConversationGroups"];
        };
        ConversationGroups: {
            needsAttention: components["schemas"]["ConversationCard"][];
            caughtUp: components["schemas"]["ConversationCard"][];
            inactive: components["schemas"]["ConversationCard"][];
            archived: components["schemas"]["ConversationCard"][];
            available: components["schemas"]["ConversationCard"][];
            moderating: components["schemas"]["ConversationCard"][];
        };
        ConversationCard: {
            slug: string;
            title: string;
            /** @enum {string} */
            relationship: "joined" | "available" | "moderating";
            participantState: ("needs_attention" | "caught_up" | "inactive" | "archived") | null;
            pseudonym: string | null;
            /** @enum {string} */
            status: "open" | "paused" | "archived";
            phases: string[];
            statementsRemaining: number | null;
            scheduledTransition: components["schemas"]["ScheduledTransition"] | null;
            outputs: components["schemas"]["ConversationOutput"][];
            capabilities: components["schemas"]["ConversationCapabilities"];
            links: components["schemas"]["ConversationLinks"];
        };
        ConversationAboutResponse: {
            data: components["schemas"]["ConversationAbout"];
        };
        PseudonymSuggestionsResponse: {
            data: {
                pseudonyms: string[];
            };
        };
        CreateParticipationRequest: {
            pseudonym: string;
            /** @default false */
            notifyEmail: boolean;
            /** @default false */
            notifyTalkPage: boolean;
        };
        ParticipationResponse: {
            data: components["schemas"]["Participation"];
        };
        Participation: {
            pseudonym: string;
            notifications: {
                email: boolean;
                talkPage: boolean;
            };
            /** @enum {string|null} */
            eligibilityStatus: "eligible" | "not_required" | null;
            links: {
                conversation: string;
                about: string;
            };
        };
        ExploreStateResponse: {
            data: components["schemas"]["ExploreState"];
        };
        ExploreState: {
            slug: string;
            title: string;
            pseudonym: string;
            currentStatement: components["schemas"]["ExploreStatement"] | null;
            progress: components["schemas"]["ExploreProgress"];
            newStatement: components["schemas"]["NewStatementAvailability"];
            capabilities: components["schemas"]["ExploreCapabilities"];
            links: components["schemas"]["ExploreLinks"];
        };
        ExploreStatement: {
            id: number;
            text: string;
            isMeta: boolean;
            isSeed: boolean;
        };
        ExploreProgress: {
            completed: number;
            total: number;
            remaining: number;
            allDone: boolean;
        };
        NewStatementAvailability: {
            unlocked: boolean;
            unlockAfter: number;
            quota: number;
            used: number;
            remaining: number;
        };
        ExploreCapabilities: {
            vote: boolean;
            suggestWording: boolean;
            submitNewStatement: boolean;
        };
        ExploreLinks: {
            self: string;
            about: string;
            conversation: string;
        };
        ExploreVoteRequest: {
            /** @enum {string} */
            choice: "agree" | "pass" | "disagree";
        };
        ExploreVoteResponse: {
            data: components["schemas"]["ExploreVoteReceipt"];
        };
        ExploreVoteReceipt: {
            statementId: number;
            /** @enum {string} */
            choice: "agree" | "pass" | "disagree";
            links: {
                explore: string;
            };
        };
        CreateStatementRequest: {
            text: string;
            derivedFromStatementId?: number | null;
        };
        StatementCreationResponse: {
            data: components["schemas"]["StatementCreationReceipt"];
        };
        StatementCreationReceipt: {
            statementId: number;
            /** @enum {string} */
            kind: "new" | "derivative";
            derivedFromStatementId: number | null;
            newStatementQuotaRemaining: number;
            links: {
                explore: string;
            };
        };
        ConversationAbout: {
            slug: string;
            title: string;
            descriptionHtml: string | null;
            outroHtml: string | null;
            /** @enum {string} */
            status: "open" | "paused" | "archived";
            phases: components["schemas"]["ConversationPhase"][];
            scheduledTransition: components["schemas"]["ScheduledTransition"] | null;
            pseudonym: string | null;
            statistics: components["schemas"]["ConversationStatistics"];
            personal: components["schemas"]["PersonalContributions"] | null;
            outputs: components["schemas"]["ConversationOutput"][];
            moderation: components["schemas"]["ConversationModeration"];
            capabilities: components["schemas"]["ConversationAboutCapabilities"];
            links: components["schemas"]["ConversationAboutLinks"];
        };
        ConversationPhase: {
            key: string;
            label: string;
        };
        ConversationStatistics: {
            participants: number | null;
            statementVotes: number | null;
            statements: number | null;
            arguments: number;
            argumentContributors: number;
        };
        PersonalContributions: {
            statementsSuggested: number;
            statementVotes: number | null;
            statementVotesAvailable: boolean;
            argumentsAdded: number;
            argumentsRated: number;
        };
        ConversationModeration: {
            eventCount: number;
            href: string;
        };
        ConversationAboutCapabilities: {
            participate: boolean;
            moderate: boolean;
        };
        ConversationAboutLinks: {
            self: string;
            conversation: string;
        };
        ScheduledTransition: {
            /** Format: date-time */
            at: string;
            target: string;
            targetLabel: string;
        };
        ConversationOutput: {
            key: string;
            label: string;
            status: string;
            ready: boolean;
            href: string | null;
        };
        ConversationCapabilities: {
            join: boolean;
            participate: boolean;
            moderate: boolean;
        };
        ConversationLinks: {
            self: string;
            about: string;
            explore?: string;
            admin?: string;
        };
        ErrorResponse: {
            error: {
                code: string;
                message: string;
                details?: unknown;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current session */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
        };
    };
    getConversationLane: {
        parameters: {
            query?: {
                space?: "real" | "demo";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Conversation lane */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationLaneResponse"];
                };
            };
            /** @description Invalid space */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getConversationAbout: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Conversation record */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationAboutResponse"];
                };
            };
            /** @description The current browser cannot access this conversation */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conversation not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getPseudonymSuggestions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fresh pseudonym suggestions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PseudonymSuggestionsResponse"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createParticipation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateParticipationRequest"];
            };
        };
        responses: {
            /** @description Existing participation returned for an idempotent replay */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParticipationResponse"];
                };
            };
            /** @description Participation created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParticipationResponse"];
                };
            };
            /** @description Invalid command */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Access or eligibility denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Pseudonym conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getExploreState: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current Explore state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExploreStateResponse"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conversation access denied or participant banned */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Participation or Explore phase is not active */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Voting service unavailable */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    putExploreVote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                statementId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExploreVoteRequest"];
            };
        };
        responses: {
            /** @description Vote stored */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExploreVoteResponse"];
                };
            };
            /** @description Invalid vote choice */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conversation access denied or participant banned */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conversation or statement not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Participation or Explore phase is not active */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Voting service unavailable */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createStatement: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStatementRequest"];
            };
        };
        responses: {
            /** @description Completed command replay */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatementCreationResponse"];
                };
            };
            /** @description Statement created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatementCreationResponse"];
                };
            };
            /** @description Invalid request, idempotency key, or parent statement */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conversation access denied or participant banned */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Quota, derivative similarity, idempotency conflict, or unknown outcome */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The upstream command outcome is unknown */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getOpenApiDocument: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OpenAPI 3.1 document */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
