/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the current browser session and its site-wide capabilities */
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return participant-facing conversation groups for one space */
        get: operations["getConversationLane"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return this OpenAPI document */
        get: operations["getOpenApiDocument"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SessionResponse: {
            data: components["schemas"]["Session"];
        };
        Session: {
            /** @enum {string} */
            state: "anonymous" | "authenticated" | "demo";
            user: components["schemas"]["SessionUser"] | null;
            capabilities: components["schemas"]["SiteCapabilities"];
            csrfToken: string;
            links: components["schemas"]["SessionLinks"];
        };
        SessionUser: {
            username: string;
            emailable: boolean;
        };
        SiteCapabilities: {
            administerSite: boolean;
        };
        SessionLinks: {
            login: string;
            logout: string;
        };
        ConversationLaneResponse: {
            data: components["schemas"]["ConversationLane"];
        };
        ConversationLane: {
            /** @enum {string} */
            space: "real" | "demo";
            authenticated: boolean;
            groups: components["schemas"]["ConversationGroups"];
        };
        ConversationGroups: {
            needsAttention: components["schemas"]["ConversationCard"][];
            caughtUp: components["schemas"]["ConversationCard"][];
            inactive: components["schemas"]["ConversationCard"][];
            archived: components["schemas"]["ConversationCard"][];
            available: components["schemas"]["ConversationCard"][];
            moderating: components["schemas"]["ConversationCard"][];
        };
        ConversationCard: {
            slug: string;
            title: string;
            /** @enum {string} */
            relationship: "joined" | "available" | "moderating";
            participantState: ("needs_attention" | "caught_up" | "inactive" | "archived") | null;
            pseudonym: string | null;
            /** @enum {string} */
            status: "open" | "paused" | "archived";
            phases: string[];
            statementsRemaining: number | null;
            scheduledTransition: components["schemas"]["ScheduledTransition"] | null;
            outputs: components["schemas"]["ConversationOutput"][];
            capabilities: components["schemas"]["ConversationCapabilities"];
            links: components["schemas"]["ConversationLinks"];
        };
        ScheduledTransition: {
            /** Format: date-time */
            at: string;
            target: string;
            targetLabel: string;
        };
        ConversationOutput: {
            key: string;
            label: string;
            status: string;
            ready: boolean;
            href: string | null;
        };
        ConversationCapabilities: {
            join: boolean;
            participate: boolean;
            moderate: boolean;
        };
        ConversationLinks: {
            self: string;
            admin?: string;
        };
        ErrorResponse: {
            error: {
                code: string;
                message: string;
                details?: unknown;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current session */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
        };
    };
    getConversationLane: {
        parameters: {
            query?: {
                space?: "real" | "demo";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Conversation lane */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationLaneResponse"];
                };
            };
            /** @description Invalid space */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getOpenApiDocument: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OpenAPI 3.1 document */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
